# Generated by Django 5.2 on 2025-04-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0002_alter_comment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={},
        ),
    ]
